apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-huelights
  labels:
    app: huelights
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/jj