apiVersion: v1
kind: Service
metadata:
  name: huelights-lb-80
  labels:
    app: huelights
spec:
  selector:
    app: huelights
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  # - port: 5000
  #   targetPort: 5000